# Generated by Django 6.0.3 on 2026-03-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
